/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface ModelAndView {
    

    empty?: boolean;

    model?: any;

    modelMap?: { [key: string]: any; };

    reference?: boolean;

    status?: ModelAndView.StatusEnum;

    view?: models.View;

    viewName?: string;
}
export namespace ModelAndView {

    export enum StatusEnum { 
        100 = <any> '100',
        101 = <any> '101',
        102 = <any> '102',
        103 = <any> '103',
        200 = <any> '200',
        201 = <any> '201',
        202 = <any> '202',
        203 = <any> '203',
        204 = <any> '204',
        205 = <any> '205',
        206 = <any> '206',
        207 = <any> '207',
        208 = <any> '208',
        226 = <any> '226',
        300 = <any> '300',
        301 = <any> '301',
        302 = <any> '302',
        303 = <any> '303',
        304 = <any> '304',
        305 = <any> '305',
        307 = <any> '307',
        308 = <any> '308',
        400 = <any> '400',
        401 = <any> '401',
        402 = <any> '402',
        403 = <any> '403',
        404 = <any> '404',
        405 = <any> '405',
        406 = <any> '406',
        407 = <any> '407',
        408 = <any> '408',
        409 = <any> '409',
        410 = <any> '410',
        411 = <any> '411',
        412 = <any> '412',
        413 = <any> '413',
        414 = <any> '414',
        415 = <any> '415',
        416 = <any> '416',
        417 = <any> '417',
        418 = <any> '418',
        419 = <any> '419',
        420 = <any> '420',
        421 = <any> '421',
        422 = <any> '422',
        423 = <any> '423',
        424 = <any> '424',
        426 = <any> '426',
        428 = <any> '428',
        429 = <any> '429',
        431 = <any> '431',
        451 = <any> '451',
        500 = <any> '500',
        501 = <any> '501',
        502 = <any> '502',
        503 = <any> '503',
        504 = <any> '504',
        505 = <any> '505',
        506 = <any> '506',
        507 = <any> '507',
        508 = <any> '508',
        509 = <any> '509',
        510 = <any> '510',
        511 = <any> '511',
    }
}
